# Generated by Django 5.0.1 on 2024-01-29 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_userprofile_profile_picture_and_more"),
        ("store", "0005_auto_20210321_0717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.account"
            ),
        ),
    ]
